### ISSUE TITLE
Encoding Error in Debug Log

### ISSUE THREAD

**Issue by jimcampbell100** [patzm/plex-music-rating-sync#17]
When the song title uses a character that can't be encoded, the following error is raised when the debug message is written to sync_ratings.log:

> --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\jim\miniconda3\envs\syncratings\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\jim\miniconda3\envs\syncratings\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 92: character maps to <undefined>
Call stack:
  File "G:\Portable Installations\python\plex-music-rating-sync\sync_ratings.py", line 180, in <module>
    sync_agent.sync()
  File "G:\Portable Installations\python\plex-music-rating-sync\sync_ratings.py", line 109, in sync
    self.sync_tracks()
  File "G:\Portable Installations\python\plex-music-rating-sync\sync_ratings.py", line 131, in sync_tracks
    if pair.match(): matched += 1
  File "G:\Portable Installations\python\plex-music-rating-sync\sync_pair.py", line 131, in match
    self.logger.debug('Found match with score {} for {}: {}'.format(
Message: 'Found match with score 100.0 for American Hi‐Fi - American Hi‐Fi - I’m a Fool: American Hi‐Fi - American Hi‐Fi - I’m a Fool'
Arguments: ()

This can be corrected by making the following change to line 58 of sync_ratings.py (to specify the encoding of the file being written to):

>fh = logging.FileHandler(filename='sync_ratings.log', encoding='utf-8', mode='w')

**Comment by smilerz** [comment]
thanks! fixed
